spring:
  rabbitmq:
    host: 192.3.128.13 # RabbitMQ服务器地址
    port: 5672 # RabbitMQ服务器端口
    virtual-host: / # RabbitMQ虚拟主机
    username: itcast # RabbitMQ用户名
    password: 123321 # RabbitMQ密码
    listener:
      simple:
        acknowledge-mode: manual # 手动确认
        concurrency: 1 # 消费者线程数
        max-concurrency: 1 # 最大消费者线程数
        prefetch: 1 # 每次消费的消息数量，即每次消费一个消息
        retry:
          enabled: true # 开启重试
          max-attempts: 3 # 最大重试次数
          initial-interval: 1000 # 重试间隔
          max-interval: 10000   # 最大重试间隔
          multiplier: 2 # 重试间隔倍数
          stateless: true # 重试间隔倍数
logging:
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss
